language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: stable
  - rust: beta

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script: # 集成脚本
- cargo build --all --all-features
- cargo test --all --all-features

after_success:
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - travis-cargo coveralls --no-sudo --verify

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=
    - secure: dR87HoAxUa+mhndChdSD9cbbhMOo1M/cyJ+zzF59WZJ4es2BObCXLQTHXGNAuIY5BCYUIVz6uQCET8qgVyezTWF5c24dUhLOCBrja61p9IF0j+Km6hX3ttgsyW4IImj9NvniDi5CirpdwP7oO+5/OMsSFDOQOYCxjtGME3FcWEziIZ0zWEN+psqD0u7zjn0LypZexcw2oLmMdAfpK5+5s+oSq40CbPs+vYV8Jd8u/3KIvUQeOiEveEVvfah7XZejpsQRsHnMP9mK/A6jecE2KIZCBD6JHmWOmGGqD6xmuLu9wngspnonD8WWKO37rZkD/ckIdSDWKYB0WNaWVpPdK03Nfeg3fcgiaW14MJi5lK5W0cPCaRGJN4tkT6pE41qg0OHprmbM3Xew/2Q8zvxvoAwwal/muKPA0Yd6a936R1JZMd1VQ2pl+773GDbMSQjvAmEIRNDXSHkqVAkp8qXxQkhlFX9q4Ij6RTCZgaC5TLoNMqF7wQ6yBzZrKhcXgVn/SIJJNTyGgrCtTT41pxqAnat+MC4bFUOsbLxl4pEd/WfllBRYHTrvBI5UanS90/D2r4LvUfNwP+P5uqosVajc7ZZq+nkXXK61SKAYVzyZoEuf7eU5sc5Wx3Gv+sHQghPBLcTnYL0XMQTHqNkaJVn+Li+mZpOwyZokoMJhVSRAXC8=
    - secure: l9ldguTRiiu26dX4juUXr/JNQ7gSZhIWpq4kHqw58dWn89zN53fqHqSq3yP48BhpwxoRhfkauHRw7FwpRtWEIsllWE+i7AWOfqEcNcP3eSx8XKattsFKPSv44K8AAnmEoBSngt4yuTG/57u8Dq8xF6Lsn32I43S2D4RoUrHpP66y7BH4pVm2MS/qt79bbC6rF1ajr4YnofyYELaAPgPzTxxbtISTP1rQzmc047oYFdP2cXJNzE8rzTHDk16YI4JMah2PKMIRSExAVZ9S4x/Oov5DU3gDIw9dupUoeTb1ssnH1CVRUpUEfBWS5HkL28wEtUIwFytj8lz8sMROjO95p1XRlYhxY+905WHSbNJ1xfk1eYTaUROOsVwoSVWuoLlUJFTRAc26tKlM4L4GKwpQiySrk17Lym9oDwEsVuf9cV0Dg4k86VLVru+qIHICV2DEsJD7fIlXp6e+R44z4G6KgY7g/lWbfKOz5zROm1B3fhNuUh/2WJ9kOx6wmArg6SfZ6BpnXoDEOJoUchXG88+fSi6rUTlxkpKHBzZqpbzu1MqNmvn7LCGrh6iFgn2ca7xKTxBzPPV+paA+9HsMsTvLCm6yUFG8kLi4ha1Jdc1zKj2CSFLxqhUHdGhVD+n9X61nQjJQ6PSx8rv+T0UQQPcmLiEONmlQ03aM7GHrOc2+fC8=
    - secure: p+Yi3Ul4joj5op23BZjBZPjXSv2BiC1772ONGqhxPqJaIqk1Vs0zzNv8LbaTzWUUUB9pyETR8XHAnz8wfKtSwTEg5w0AUzExlGijl39xWrE1NiHKlv5PVgGssJDI7fFdvp3Ss8KBVwaMjMCOAB/wbb8sjZstpnKE5Ge2YT6iw/L/Xo8V6LBZY1wGiosxW9vGcoomhIYWjzDryY9Pwaq0J1kEEEsF+OIJHq/9xW5xuxbJrCBue7+YNoyANvlgxniy0+BBAXtq/cHlNokR/8tD1xHot99X/HemG/oASM9QDR+TCDRQNW/jadSc2xAUEChUCLWhv+euuDpzL6y1G7sOqwD24tyT1/5dLY1Rryf/pi69Z5KmjdhKemNrPyUElyTSCWz9pLEfQFMpntMMM6We12XGw+SOo9pvQYpyF1Y1NkGruOCTbNApfOl9Xio3PTYwNpP1kKToBmHZy2sr7gblxm8uunKfCk83Cz/8qxOTqjowbm4d1pHAkGIVCmUnX7e9YOVDDEsLCb37vCAPXwM3U35MEqRAncjJCSoGWo6WxLAnqGJTv2bJdICXpGs1zgT8ywbjPiIoHYUgt5zIhDcr18CjwIrAWTzCnMQQePduTW022QNV5c+zg3tI1DkgsLEDu0sSOPWjHhIYmS6beSooEc+abm1om8/gGBsTxkq5Lts=

notifications:
  email:
    recipients:
    - hexileee@gmail.com
  on_success: change
  on_failure: always